# Site settings
title: Commando
email: geoff@lentner.io
description: C++ Command Line Interfaces Made Easy
baseurl: /Commando/"" # the subpath of your site, e.g. /blog/
url: "http://lentner.io" # the base hostname & protocol for your site

twitter_username: Geoffrey
github_username: glentner

# Build settings
markdown: kramdown
